TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64
INGREDIENT_MIN_AMOUNT_VALUE = 1
INGREDIENT_MAX_AMOUNT_VALUE = 32767

RECIPE_NAME_MAX_LENGTH = 256
RECIPE_COOKING_TIME_MIN_VALUE = 1
RECIPE_COOKING_TIME_MAX_VALUE = 32767
